owner: mirzahilmi
repo: uptime

sites:
  - name: Grafana
    url: https://grafana.mrz.my.id/api/health

assignees:
  - mirzahilmi

status-website:
  cname: status.mrz.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Mirza's Managed Sites Uptime Status (MMSUS)
  introMessage: Hello, World!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
